---
# yamllint disable rule:line-length

apiVersion: batch/v1
kind: Job
metadata:
  name: s3-wif-demo
  namespace: 
spec:
  template:
    spec:
      automountServiceAccountToken: true
      serviceAccount: s3-wif-demo
      containers:
      - name: hello-kubernetes
        image: docker.io/dronenb/toolbox@sha256:55083b7d1ecb05ff1f8a5b1d293ca613e7385475ae3f43bab073e05fa3f33939
        command: ["/bin/bash", "-c"]
        volumeMounts:
          - name: credential-config-volume
            mountPath: /config
          - name: tokens
            mountPath: /var/run/secrets/kubernetes.io/tokens
        args:
          - |
            sleep infinity
            # Add your custom commands here
            gcloud auth login --cred-file=/config/credential-configuration.json
            az login \
              --allow-no-subscriptions \
              --service-principal \
              --tenant d56a3b3a-f480-4f7c-ae4b-19a0784de9eb \
              --username 21948c7f-34da-4aef-9f10-31e91e24b0f4 \
              --federated-token $(cat /var/run/secrets/kubernetes.io/tokens/azure-token)
              # https://docs.aws.amazon.com/IAM/latest/UserGuide/sts_example_sts_AssumeRoleWithWebIdentity_section.html
      restartPolicy: Never
      volumes:
        - name: credential-config-volume
          configMap:
            name: credential-config
        - name: tokens
          projected:
            sources:
              - serviceAccountToken:
                  path: gcp-token
                  expirationSeconds: 3600
                  audience: https://iam.googleapis.com/projects/576089806637/locations/global/workloadIdentityPools/dronenb-kubecon-2024-demo/providers/kubecon-2024-demo
              - serviceAccountToken:
                  path: azure-token
                  expirationSeconds: 3600
                  audience: api://AzureADTokenExchange
              - serviceAccountToken:
                  path: aws-token
                  expirationSeconds: 3600
                  audience: sts.amazonaws.com
  backoffLimit: 4
