---
apiVersion: v1
kind: Pod
metadata:
  name: secrets-demo
  namespace: default
spec:
  serviceAccount: default
  containers:
    - image: registry.access.redhat.com/ubi9/ubi-minimal@sha256:c0e70387664f30cd9cf2795b547e4a9a51002c44a4a86aa9335ab030134bf392
      imagePullPolicy: IfNotPresent
      name: mypod
      resources:
        requests:
          cpu: 100m
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      command: ["/usr/bin/sleep", "infinity"]
      volumeMounts:
        - mountPath: "/var/run/secrets/awssecrets"
          name: awssecrets
        - mountPath: "/var/run/secrets/azuresecrets"
          name: azuresecrets
        - mountPath: "/var/run/secrets/gcpsecrets"
          name: gcpsecrets
  volumes:
    - name: awssecrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws"
    - name: azuresecrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure"
    - name: gcpsecrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "gcp"