apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp
  namespace: default
spec:
  provider: gcp
  parameters:
    auth: pod-adc
    secrets: |
      - resourceName: "projects/dronenb-kubecon-2024-demo/secrets/example-gcp-secret/versions/latest"
        path: "example-gcp-secret"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    tenantID: "d56a3b3a-f480-4f7c-ae4b-19a0784de9eb"
    clientID: "21948c7f-34da-4aef-9f10-31e91e24b0f4"
    keyvaultName: "kubecon-2024-demo"
    objects: |
      array:
        - |
          objectName: example-azure-secret
          objectType: secret
          objectVersion: ""
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws
  namespace: default
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:726600616558:secret:example-aws-secret-5L2mYm"
        objectType: "secretsmanager"
